# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080

LABEL io.openschift.expose-servicelabe="8080:http" \
      io.k8s.deplay-name="Apache http server" \
      io.openschift.tags="apache, httpd"
RUN sed "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    sed "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd
USER 1001
	
			
